### ISSUE TITLE
MatrixFactorization() incompatible with Python 3.6.x

### ISSUE THREAD

**Issue by adam-erickson** [hammerlab/fancyimpute#38] opened 2017-08-31 17:17 UTC
It works with Python 2.7.13. I assume this is due to the **downhill** package?

**Comment by sergeyf** [comment] 2017-08-31 17:21
`downhill` looks py3 compatible. What's your error message?

**Comment by adam-erickson** [comment] 2017-08-31 18:39
It was an error about writing to file. I think it was from `climate` package logging.

**Comment by sergeyf** [comment] 2017-08-31 18:42
Not sure. `climate` should work for py2 and py3 according to this: http://py-cli.readthedocs.io/en/stable/quickstart.html#installation

Do you have a small snippet to reproduce?

**Comment by adam-erickson** [comment] 2017-08-31 18:44
I don't unfortunately, but I should be able to reproduce it later with a synthetic dataset.

**Comment by sergeyf** [comment] 2017-08-31 18:46
Sounds good thanks!

**Comment by dburkhardt** [comment] 2017-10-09 19:56
I have been able to use MatrixFactorization() with Python 3.2.6.

**Comment by vanJargon** [comment] 2017-10-18 17:30
I encountered the same error using MatrixFactorization() on Python 3.6.2 with a synthetic dataset.

```
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-19-3c3a54d11ab7> in <module>()
      5 a = np.array([[0,1,np.NaN],[1,np.NaN,1],[np.NaN,1,2]])
      6 
----> 7 X_filled_nnm = MatrixFactorization().complete(a)

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/fancyimpute/solver.py in complete(self, X)
    205         Returns completed matrix without any NaNs.
    206         """
--> 207         imputations = self.multiple_imputations(X)
    208         if len(imputations) == 1:
    209             return imputations[0]

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/fancyimpute/solver.py in multiple_imputations(self, X)
    197         Generate multiple imputations of the same incomplete matrix
    198         """
--> 199         return [self.single_imputation(X) for _ in range(self.n_imputations)]
    200 
    201     def complete(self, X):

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/fancyimpute/solver.py in <listcomp>(.0)
    197         Generate multiple imputations of the same incomplete matrix
    198         """
--> 199         return [self.single_imputation(X) for _ in range(self.n_imputations)]
    200 
    201     def complete(self, X):

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/fancyimpute/solver.py in single_imputation(self, X)
    182                     type(X_filled)))
    183 
--> 184         X_result = self.solve(X_filled, missing_mask)
    185         if not isinstance(X_result, np.ndarray):
    186             raise TypeError(

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/fancyimpute/matrix_factorization.py in solve(self, X, missing_mask)
     94             learning_rate=self.learning_rate,
     95             monitors=[("error", err.mean())],
---> 96             monitor_gradients=self.verbose)
     97 
     98         U_value = U.get_value()

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/downhill/__init__.py in minimize(loss, train, valid, params, inputs, algo, updates, monitors, monitor_gradients, batch_size, train_batches, valid_batches, **kwargs)
     72             name='train',
     73             batch_size=batch_size,
---> 74             iteration_size=train_batches,
     75         )
     76     if valid is not None and not isinstance(valid, Dataset):

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/downhill/dataset.py in __init__(self, inputs, name, batch_size, iteration_size, axis, rng)
    104             self._init_callable(inputs)
    105         else:
--> 106             self._init_arrays(inputs, axis)
    107 
    108     def _init_callable(self, inputs):

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/downhill/dataset.py in _init_arrays(self, inputs, axis)
    168         click.echo('{}: {} of {} mini-batches from {}'.format(
    169             self.name, self.iteration_size, len(self._slices),
--> 170             '; '.join(str(s) for s in shapes)))
    171 
    172     def __iter__(self):

~/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/click/utils.py in echo(message, file, nl, err, color)
    257 
    258     if message:
--> 259         file.write(message)
    260     file.flush()
    261 

UnsupportedOperation: not writable
```

**Comment by sergeyf** [comment] 2017-10-18 17:43
Oh boy `downhill` is really causing a lot of trouble. @iskandr maybe we should try to swap it out for something else and stop being dependent on `theano`? Tensorflow is really a lot easier to install now.

**Comment by adam-erickson** [comment] 2017-10-18 17:48
@vanJargon Thank you for confirming!

**Comment by sergeyf** [comment] 2017-10-22 17:28
This doesn't seem to be a `theano` bug, but we've had a bunch of tickets opened where the root cause was `downhill` or one of its requirements, so I'm wondering if there's another package that we could rely on for just the explicit matrix factorization part.

Some options off the top of my head:

1. We can just pretend every missing-data problem is an implicit factorization problem and use, say: https://github.com/benfred/implicit. I can't tell if this is a good idea or just plain foolish.

2. @iskandr and/or I can rewrite the optimization that's currently done in `downhill` in, for example, `keras` + `tensorflow` ourselves. I would suggest `pytorch`, but it doesn't have out-of-the-box Windows support yet. I don't want to damn our Windows users. 

I'm leaning towards the latter because my idea of fun is redoing other people's work.

**Comment by sergeyf** [comment] 2017-10-22 21:35
Here's a proposed `keras` model and a basic usage example: https://gist.github.com/sergeyf/dc1b8ee21e6be634dcb311bd858ec567

From some quick experiments on some `sklearn` datasets, it seems that the l2 regularization and `latent_dim` parameters are pretty important, but I am not sure how to set it properly without cross-validation, which is expensive. Open to ideas.

**Comment by iskandr** [comment] 2017-10-23 15:46
I looked over the gist and it looks great. I think the results from this approach might differ slightly from the version I wrote with downhill (e.g. different regularizer) but neither is obviously optimal or robust, so differences seem acceptable.

**Comment by sergeyf** [comment] 2017-10-23 19:11
PR is here: https://github.com/hammerlab/fancyimpute/pull/41

One issue is that the Keras version is simply not as good on the toy problem. I don't know why.

**Comment by sergeyf** [comment] 2017-11-21 01:31
OK I merged it. The dependency on theano is gone - instead you'll need keras and tensorflow. Feel free to try it out and provide feedback.

 @iskandr will you please update the pypi repo?

**Comment by iskandr** [comment] 2017-12-28 21:42
@sergeyf You updated pypi already, right? Can we close this issue?

**Comment by sergeyf** [comment] 2017-12-28 22:58
I haven't! Do you mind doing it?

**Comment by iskandr** [comment] 2017-12-29 00:31
Ah, I need to bump the version up. I'll do it later tonight.

**Comment by sergeyf** [comment] 2017-12-29 00:33
I thank you. Also, maybe we can figure out why the Keras SGD version of
matrix factorization is worse than the downhill? Maybe it needs RANDOM SGD!

**Comment by iskandr** [comment] 2017-12-29 17:53
Uploaded!

**Comment by sergeyf** [comment] 2017-12-29 17:58
Thank you!

**Closed by sergeyf** 2017-12-29 17:58 UTC

**Comment by PEE8** [comment] 2018-08-08 12:57
how to install sgd on anaconda on windows 7 64-bit.

Please let me know. thank you

**Comment by tasmiaorni** [comment] 2019-03-06 04:05
Hello , I installed fancyimpute using "pip install fancyimpute"
When I am importing it like "import fancyimpute"
But I am getting this error:

![image](https://user-images.githubusercontent.com/31642602/53855302-05206280-3f9b-11e9-9638-c0a5bce0c4a1.png)

**Comment by sergeyf** [comment] 2019-03-06 04:21
You only pasted a partial error. Can you paste the whole error?

**Comment by tasmiaorni** [comment] 2019-03-06 04:28
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python37\Lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\Lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Tasmia Aqila/PycharmProjects/Data_visualization/practice.py", line 4, in <module>
    from fancyimpute import KNN, NuclearNormMinimization, SoftImpute, IterativeImputer, BiScaler
  File "C:\Python37\Lib\site-packages\fancyimpute\__init__.py", line 6, in <module>
    from .matrix_factorization import MatrixFactorization
  File "C:\Python37\Lib\site-packages\fancyimpute\matrix_factorization.py", line 16, in <module>
    from keras import regularizers
  File "C:\Python37\Lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Python37\Lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Python37\Lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Python37\Lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Python37\Lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Python37\Lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Python37\Lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python37\Lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\Lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

**Comment by sergeyf** [comment] 2019-03-06 04:36
Looks like your tensorflow install is broken. If you just `import tensorflow` does that work? If not, you have to fix tensorflow first. I would google for that one - it's not a problem we can fix here.

**Comment by tasmiaorni** [comment] 2019-03-06 04:44
Yes I think tensorflow is broken. I installed through "pip install tensorflow" .I t installed successfully but If I write "import tensorflow" it gives error.

I am using python 3.7.do u think that is the reason??

**Comment by sergeyf** [comment] 2019-03-06 05:29
Sorry, I don't really know!
